/*
 * Copyright (C) 2017 by Sebastian Hasait (sebastian at hasait dot de)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package de.hasait.cipa.test

import hudson.model.Job
import hudson.model.Run
import hudson.tasks.junit.CaseResult
import hudson.tasks.junit.TestResultAction
import org.mockito.Mockito

/**
 *
 */
class TestPipelineTest {

	static void main(String[] args) {
		System.out.println("Test")

		Run run = Mockito.mock(Run)
		TestResultAction testResultAction = Mockito.mock(TestResultAction)
		CaseResult caseResult1 = Mockito.mock(CaseResult)
		Mockito.when(caseResult1.getClassName()).thenReturn('foo.bar.SddTest')
		Mockito.when(testResultAction.getPassedTests()).thenReturn([caseResult1])
		Mockito.when(run.getAction(TestResultAction.class)).thenReturn(testResultAction)
		Job job = Mockito.mock(Job)
		Mockito.when(run.getParent()).thenReturn(job)
		Mockito.when(job.getDescription()).thenReturn('''
vvv parameters.json vvv {
  "MAIN_SCM_URL": "scm://somewhere.git"
, "MAIN_SCM_CREDENTIALS_ID": "somecreds"
} ^^^ parameters.json ^^^
''')

		TestRawScript rawScript = new TestRawScript()
		rawScript.currentBuild.rawBuild = run

		rawScript.readFileContents.put('activities-graph\\.svg', '''
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
 "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Generated by graphviz version 2.38.0 (20140413.2041)
 -->
<!-- Title: pipeline Pages: 1 -->
<svg width="822pt" height="267pt"
 viewBox="0.00 0.00 822.00 267.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 263)">
<title>pipeline</title>
<polygon fill="white" stroke="none" points="-4,4 -4,-263 818,-263 818,4 -4,4"/>
<g id="clust1" class="cluster"><title>cluster_node0</title>
<polygon fill="none" stroke="black" stroke-dasharray="1,5" points="82,-134 82,-209 277,-209 277,-134 82,-134"/>
<text text-anchor="middle" x="179.5" y="-193.8" font-family="Times,serif" font-size="14.00">node1</text>
</g>
<g id="clust2" class="cluster"><title>cluster_node1</title>
<polygon fill="none" stroke="black" stroke-dasharray="1,5" points="297,-8 297,-251 806,-251 806,-8 297,-8"/>
<text text-anchor="middle" x="551.5" y="-235.8" font-family="Times,serif" font-size="14.00">node2</text>
</g>
<!-- a0 -->
<g id="node1" class="node"><title>a0</title>
<polygon fill="none" stroke="black" points="158,-178 90,-178 90,-142 158,-142 158,-178"/>
<text text-anchor="middle" x="124" y="-156.3" font-family="Times,serif" font-size="14.00">Checkout</text>
</g>
<!-- a1 -->
<g id="node2" class="node"><title>a1</title>
<polygon fill="none" stroke="black" points="269,-178 194,-178 194,-142 269,-142 269,-178"/>
<text text-anchor="middle" x="231.5" y="-156.3" font-family="Times,serif" font-size="14.00">StashMain</text>
</g>
<!-- a0&#45;&gt;a1 -->
<g id="edge2" class="edge"><title>a0&#45;&gt;a1</title>
<path fill="none" stroke="black" d="M158.091,-160C166.257,-160 175.156,-160 183.832,-160"/>
<polygon fill="black" stroke="black" points="183.858,-163.5 193.858,-160 183.858,-156.5 183.858,-163.5"/>
</g>
<!-- a2 -->
<g id="node3" class="node"><title>a2</title>
<polygon fill="none" stroke="black" points="394,-178 305,-178 305,-142 394,-142 394,-178"/>
<text text-anchor="middle" x="349.5" y="-156.3" font-family="Times,serif" font-size="14.00">UnstashMain</text>
</g>
<!-- a1&#45;&gt;a2 -->
<g id="edge3" class="edge"><title>a1&#45;&gt;a2</title>
<path fill="none" stroke="black" d="M269.203,-160C277.313,-160 286.069,-160 294.7,-160"/>
<polygon fill="black" stroke="black" points="294.728,-163.5 304.728,-160 294.728,-156.5 294.728,-163.5"/>
</g>
<!-- a3 -->
<g id="node4" class="node"><title>a3</title>
<polygon fill="none" stroke="black" points="492,-106 430,-106 430,-70 492,-70 492,-106"/>
<text text-anchor="middle" x="461" y="-84.3" font-family="Times,serif" font-size="14.00">TestRa1</text>
</g>
<!-- a2&#45;&gt;a3 -->
<g id="edge4" class="edge"><title>a2&#45;&gt;a3</title>
<path fill="none" stroke="black" d="M378.131,-141.831C392.008,-132.707 408.993,-121.539 423.888,-111.745"/>
<polygon fill="black" stroke="black" points="425.945,-114.581 432.377,-106.163 422.099,-108.732 425.945,-114.581"/>
</g>
<!-- a4 -->
<g id="node5" class="node"><title>a4</title>
<polygon fill="none" stroke="black" points="492,-52 430,-52 430,-16 492,-16 492,-52"/>
<text text-anchor="middle" x="461" y="-30.3" font-family="Times,serif" font-size="14.00">TestRa2</text>
</g>
<!-- a2&#45;&gt;a4 -->
<g id="edge5" class="edge"><title>a2&#45;&gt;a4</title>
<path fill="none" stroke="black" d="M363.748,-141.755C378.898,-121.324 404.863,-87.5915 430,-61 430.523,-60.4462 431.057,-59.8908 431.598,-59.3348"/>
<polygon fill="black" stroke="black" points="434.225,-61.6615 438.932,-52.17 429.333,-56.6541 434.225,-61.6615"/>
</g>
<!-- a5 -->
<g id="node6" class="node"><title>a5</title>
<polygon fill="none" stroke="black" points="492,-160 430,-160 430,-124 492,-124 492,-160"/>
<text text-anchor="middle" x="461" y="-138.3" font-family="Times,serif" font-size="14.00">TestRa3</text>
</g>
<!-- a2&#45;&gt;a5 -->
<g id="edge6" class="edge"><title>a2&#45;&gt;a5</title>
<path fill="none" stroke="black" d="M394.092,-152.834C402.572,-151.44 411.425,-149.985 419.79,-148.61"/>
<polygon fill="black" stroke="black" points="420.394,-152.058 429.694,-146.982 419.258,-145.15 420.394,-152.058"/>
</g>
<!-- a6 -->
<g id="node7" class="node"><title>a6</title>
<polygon fill="none" stroke="black" points="594,-160 528,-160 528,-124 594,-124 594,-160"/>
<text text-anchor="middle" x="561" y="-138.3" font-family="Times,serif" font-size="14.00">TestWa1</text>
</g>
<!-- a2&#45;&gt;a6 -->
<g id="edge10" class="edge"><title>a2&#45;&gt;a6</title>
<path fill="none" stroke="black" d="M394.205,-168.406C422.352,-172.44 459.602,-175.197 492,-169 500.793,-167.318 509.898,-164.516 518.477,-161.338"/>
<polygon fill="black" stroke="black" points="519.872,-164.55 527.895,-157.63 517.308,-158.037 519.872,-164.55"/>
</g>
<!-- a7 -->
<g id="node8" class="node"><title>a7</title>
<polygon fill="none" stroke="black" points="696,-200 630,-200 630,-164 696,-164 696,-200"/>
<text text-anchor="middle" x="663" y="-178.3" font-family="Times,serif" font-size="14.00">TestWa2</text>
</g>
<!-- a2&#45;&gt;a7 -->
<g id="edge12" class="edge"><title>a2&#45;&gt;a7</title>
<path fill="none" stroke="black" d="M394.055,-169.487C405.679,-171.671 418.271,-173.724 430,-175 496.107,-182.189 573.388,-183.019 619.969,-182.7"/>
<polygon fill="black" stroke="black" points="620.024,-186.2 629.993,-182.61 619.962,-179.2 620.024,-186.2"/>
</g>
<!-- a8 -->
<g id="node9" class="node"><title>a8</title>
<polygon fill="none" stroke="black" points="798,-210 732,-210 732,-174 798,-174 798,-210"/>
<text text-anchor="middle" x="765" y="-188.3" font-family="Times,serif" font-size="14.00">TestWa3</text>
</g>
<!-- a2&#45;&gt;a8 -->
<g id="edge14" class="edge"><title>a2&#45;&gt;a8</title>
<path fill="none" stroke="black" d="M394.395,-173.293C405.905,-176.463 418.356,-179.614 430,-182 546.412,-205.85 578.061,-223.519 696,-209 704.507,-207.953 713.481,-206.195 722.02,-204.196"/>
<polygon fill="black" stroke="black" points="722.931,-207.577 731.792,-201.768 721.243,-200.783 722.931,-207.577"/>
</g>
<!-- a3&#45;&gt;a6 -->
<g id="edge7" class="edge"><title>a3&#45;&gt;a6</title>
<path fill="none" stroke="black" stroke-dasharray="1,5" d="M492.203,-104.642C500.639,-109.291 509.951,-114.422 518.902,-119.354"/>
<polygon fill="black" stroke="black" points="517.239,-122.434 527.686,-124.194 520.617,-116.303 517.239,-122.434"/>
</g>
<!-- a4&#45;&gt;a6 -->
<g id="edge8" class="edge"><title>a4&#45;&gt;a6</title>
<path fill="none" stroke="black" stroke-dasharray="1,5" d="M483.01,-52.2249C486.092,-55.0928 489.176,-58.0772 492,-61 508.839,-78.4293 526.391,-99.4186 539.444,-115.663"/>
<polygon fill="black" stroke="black" points="536.864,-118.042 545.832,-123.682 542.339,-113.68 536.864,-118.042"/>
</g>
<!-- a9 -->
<g id="node10" class="node"><title>a9</title>
<polygon fill="none" stroke="black" points="592,-52 530,-52 530,-16 592,-16 592,-52"/>
<text text-anchor="middle" x="561" y="-30.3" font-family="Times,serif" font-size="14.00">TestRb1</text>
</g>
<!-- a4&#45;&gt;a9 -->
<g id="edge15" class="edge"><title>a4&#45;&gt;a9</title>
<path fill="none" stroke="black" d="M492.203,-34C500.866,-34 510.452,-34 519.623,-34"/>
<polygon fill="black" stroke="black" points="519.728,-37.5001 529.728,-34 519.728,-30.5001 519.728,-37.5001"/>
</g>
<!-- a5&#45;&gt;a6 -->
<g id="edge9" class="edge"><title>a5&#45;&gt;a6</title>
<path fill="none" stroke="black" stroke-dasharray="1,5" d="M492.203,-142C500.199,-142 508.983,-142 517.5,-142"/>
<polygon fill="black" stroke="black" points="517.686,-145.5 527.686,-142 517.686,-138.5 517.686,-145.5"/>
</g>
<!-- a6&#45;&gt;a7 -->
<g id="edge11" class="edge"><title>a6&#45;&gt;a7</title>
<path fill="none" stroke="black" stroke-dasharray="1,5" d="M594.191,-154.876C602.577,-158.231 611.732,-161.893 620.524,-165.41"/>
<polygon fill="black" stroke="black" points="619.285,-168.683 629.869,-169.148 621.884,-162.184 619.285,-168.683"/>
</g>
<!-- a7&#45;&gt;a8 -->
<g id="edge13" class="edge"><title>a7&#45;&gt;a8</title>
<path fill="none" stroke="black" stroke-dasharray="1,5" d="M696.191,-185.219C704.309,-186.031 713.148,-186.915 721.681,-187.768"/>
<polygon fill="black" stroke="black" points="721.571,-191.274 731.869,-188.787 722.267,-184.309 721.571,-191.274"/>
</g>
<!-- start -->
<g id="node11" class="node"><title>start</title>
<polygon fill="none" stroke="black" points="42,-172 0,-172 0,-148 42,-148 54,-160 42,-172"/>
<text text-anchor="middle" x="27" y="-156.3" font-family="Times,serif" font-size="14.00">start</text>
</g>
<!-- start&#45;&gt;a0 -->
<g id="edge1" class="edge"><title>start&#45;&gt;a0</title>
<path fill="none" stroke="black" d="M54.2106,-160C62.1055,-160 70.9897,-160 79.6853,-160"/>
<polygon fill="black" stroke="black" points="79.7361,-163.5 89.7361,-160 79.736,-156.5 79.7361,-163.5"/>
</g>
</g>
</svg>
''')

		TestPipeline testPipeline = new TestPipeline(rawScript)
		testPipeline.run()
	}

}
