/*
 * Copyright (C) 2017 by Sebastian Hasait (sebastian at hasait dot de)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package de.hasait.cipa.test

import hudson.model.Job
import hudson.model.Run
import hudson.tasks.junit.CaseResult
import hudson.tasks.junit.TestResultAction
import org.mockito.Mockito

/**
 *
 */
class TestPipelineTest {

	static void main(String[] args) {
		System.out.println("Test")

		Run run = Mockito.mock(Run)
		TestResultAction testResultAction = Mockito.mock(TestResultAction)
		CaseResult caseResult1 = Mockito.mock(CaseResult)
		Mockito.when(caseResult1.getClassName()).thenReturn('foo.bar.SddTest')
		Mockito.when(testResultAction.getPassedTests()).thenReturn([caseResult1])
		Mockito.when(run.getAction(TestResultAction.class)).thenReturn(testResultAction)
		Job job = Mockito.mock(Job)

		TestRawScript rawScript = new TestRawScript()
		rawScript.currentBuild.rawBuild = run

		rawScript.env.MAIN_SCM_URL = 'scm://somewhere.git'
		rawScript.env.MAIN_SCM_CREDENTIALS_ID = 'somecreds'
		rawScript.env.NODE_LABEL_PREFIX = 'nlprefix-'

		rawScript.readFileContents.put('activities-graph\\.svg', '''
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
 "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Generated by graphviz version 2.38.0 (20140413.2041)
 -->
<!-- Title: pipeline Pages: 1 -->
<svg width="394pt" height="578pt"
 viewBox="0.00 0.00 394.00 578.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 574)">
<title>pipeline</title>
<polygon fill="white" stroke="none" points="-4,4 -4,-574 390,-574 390,4 -4,4"/>
<g id="clust1" class="cluster"><title>cluster_node0</title>
<polygon fill="none" stroke="black" points="214,-379 214,-526 350,-526 350,-379 214,-379"/>
<text text-anchor="middle" x="282" y="-510.8" font-family="Times,serif" font-size="14.00">node1</text>
</g>
<g id="clust2" class="cluster"><title>cluster_node1</title>
<polygon fill="none" stroke="black" points="8,-8 8,-371 378,-371 378,-8 8,-8"/>
<text text-anchor="middle" x="193" y="-355.8" font-family="Times,serif" font-size="14.00">node2</text>
</g>
<!-- a0 -->
<g id="node1" class="node"><title>a0</title>
<ellipse fill="none" stroke="black" cx="282" cy="-477" rx="55.7903" ry="18"/>
<text text-anchor="middle" x="282" y="-473.3" font-family="Times,serif" font-size="14.00">Checkout</text>
</g>
<!-- a1 -->
<g id="node2" class="node"><title>a1</title>
<ellipse fill="none" stroke="black" cx="282" cy="-405" rx="60.3893" ry="18"/>
<text text-anchor="middle" x="282" y="-401.3" font-family="Times,serif" font-size="14.00">StashMain</text>
</g>
<!-- a0&#45;&gt;a1 -->
<g id="edge2" class="edge"><title>a0&#45;&gt;a1</title>
<path fill="none" stroke="black" d="M282,-458.697C282,-450.983 282,-441.712 282,-433.112"/>
<polygon fill="black" stroke="black" points="285.5,-433.104 282,-423.104 278.5,-433.104 285.5,-433.104"/>
</g>
<!-- a2 -->
<g id="node3" class="node"><title>a2</title>
<ellipse fill="none" stroke="black" cx="282" cy="-322" rx="72.5877" ry="18"/>
<text text-anchor="middle" x="282" y="-318.3" font-family="Times,serif" font-size="14.00">UnstashMain</text>
</g>
<!-- a1&#45;&gt;a2 -->
<g id="edge3" class="edge"><title>a1&#45;&gt;a2</title>
<path fill="none" stroke="black" d="M282,-386.822C282,-376.19 282,-362.306 282,-350.204"/>
<polygon fill="black" stroke="black" points="285.5,-350.153 282,-340.153 278.5,-350.153 285.5,-350.153"/>
</g>
<!-- a3 -->
<g id="node4" class="node"><title>a3</title>
<ellipse fill="none" stroke="black" cx="59" cy="-250" rx="42.7926" ry="18"/>
<text text-anchor="middle" x="59" y="-246.3" font-family="Times,serif" font-size="14.00">TestR1</text>
</g>
<!-- a2&#45;&gt;a3 -->
<g id="edge4" class="edge"><title>a2&#45;&gt;a3</title>
<path fill="none" stroke="black" d="M238.01,-307.57C203.438,-296.965 154.091,-281.721 111,-268 107.878,-267.006 104.652,-265.971 101.409,-264.924"/>
<polygon fill="black" stroke="black" points="102.299,-261.533 91.7072,-261.778 100.14,-268.192 102.299,-261.533"/>
</g>
<!-- a4 -->
<g id="node5" class="node"><title>a4</title>
<ellipse fill="none" stroke="black" cx="163" cy="-250" rx="42.7926" ry="18"/>
<text text-anchor="middle" x="163" y="-246.3" font-family="Times,serif" font-size="14.00">TestR2</text>
</g>
<!-- a2&#45;&gt;a4 -->
<g id="edge5" class="edge"><title>a2&#45;&gt;a4</title>
<path fill="none" stroke="black" d="M254.997,-305.116C237.436,-294.786 214.426,-281.251 195.812,-270.301"/>
<polygon fill="black" stroke="black" points="197.464,-267.212 187.07,-265.159 193.915,-273.246 197.464,-267.212"/>
</g>
<!-- a5 -->
<g id="node6" class="node"><title>a5</title>
<ellipse fill="none" stroke="black" cx="267" cy="-250" rx="42.7926" ry="18"/>
<text text-anchor="middle" x="267" y="-246.3" font-family="Times,serif" font-size="14.00">TestR3</text>
</g>
<!-- a2&#45;&gt;a5 -->
<g id="edge6" class="edge"><title>a2&#45;&gt;a5</title>
<path fill="none" stroke="black" d="M278.292,-303.697C276.639,-295.983 274.653,-286.712 272.81,-278.112"/>
<polygon fill="black" stroke="black" points="276.183,-277.149 270.665,-268.104 269.338,-278.616 276.183,-277.149"/>
</g>
<!-- a6 -->
<g id="node7" class="node"><title>a6</title>
<ellipse fill="none" stroke="black" cx="267" cy="-178" rx="46.2923" ry="18"/>
<text text-anchor="middle" x="267" y="-174.3" font-family="Times,serif" font-size="14.00">TestW1</text>
</g>
<!-- a2&#45;&gt;a6 -->
<g id="edge10" class="edge"><title>a2&#45;&gt;a6</title>
<path fill="none" stroke="black" d="M297.652,-304.314C305.728,-294.538 314.758,-281.488 319,-268 323.801,-252.737 325.052,-246.811 319,-232 314.124,-220.067 305.123,-209.37 295.963,-200.763"/>
<polygon fill="black" stroke="black" points="298.141,-198.018 288.319,-194.045 293.519,-203.275 298.141,-198.018"/>
</g>
<!-- a7 -->
<g id="node8" class="node"><title>a7</title>
<ellipse fill="none" stroke="black" cx="304" cy="-106" rx="46.2923" ry="18"/>
<text text-anchor="middle" x="304" y="-102.3" font-family="Times,serif" font-size="14.00">TestW2</text>
</g>
<!-- a2&#45;&gt;a7 -->
<g id="edge12" class="edge"><title>a2&#45;&gt;a7</title>
<path fill="none" stroke="black" d="M301.015,-304.383C310.484,-294.819 320.965,-281.948 326,-268 342.337,-222.746 327.143,-166.335 315.179,-133.716"/>
<polygon fill="black" stroke="black" points="318.303,-132.088 311.452,-124.006 311.768,-134.596 318.303,-132.088"/>
</g>
<!-- a8 -->
<g id="node9" class="node"><title>a8</title>
<ellipse fill="none" stroke="black" cx="314" cy="-34" rx="46.2923" ry="18"/>
<text text-anchor="middle" x="314" y="-30.3" font-family="Times,serif" font-size="14.00">TestW3</text>
</g>
<!-- a2&#45;&gt;a8 -->
<g id="edge14" class="edge"><title>a2&#45;&gt;a8</title>
<path fill="none" stroke="black" d="M303.4,-304.602C314.277,-295.102 326.706,-282.223 334,-268 363.643,-210.201 353.424,-188.718 359,-124 360.373,-108.059 364.516,-103.019 359,-88 354.922,-76.896 347.372,-66.5265 339.605,-57.9565"/>
<polygon fill="black" stroke="black" points="341.975,-55.373 332.505,-50.6226 336.946,-60.2418 341.975,-55.373"/>
</g>
<!-- a3&#45;&gt;a6 -->
<g id="edge7" class="edge"><title>a3&#45;&gt;a6</title>
<path fill="none" stroke="black" stroke-dasharray="1,5" d="M91.5,-238.062C127.102,-226.081 184.371,-206.808 223.748,-193.556"/>
<polygon fill="black" stroke="black" points="224.989,-196.831 233.35,-190.325 222.756,-190.197 224.989,-196.831"/>
</g>
<!-- a4&#45;&gt;a6 -->
<g id="edge8" class="edge"><title>a4&#45;&gt;a6</title>
<path fill="none" stroke="black" stroke-dasharray="1,5" d="M184.802,-234.326C199.815,-224.22 219.969,-210.656 236.562,-199.487"/>
<polygon fill="black" stroke="black" points="238.527,-202.383 244.869,-193.896 234.618,-196.576 238.527,-202.383"/>
</g>
<!-- a5&#45;&gt;a6 -->
<g id="edge9" class="edge"><title>a5&#45;&gt;a6</title>
<path fill="none" stroke="black" stroke-dasharray="1,5" d="M267,-231.697C267,-223.983 267,-214.712 267,-206.112"/>
<polygon fill="black" stroke="black" points="270.5,-206.104 267,-196.104 263.5,-206.104 270.5,-206.104"/>
</g>
<!-- a6&#45;&gt;a7 -->
<g id="edge11" class="edge"><title>a6&#45;&gt;a7</title>
<path fill="none" stroke="black" stroke-dasharray="1,5" d="M275.957,-160.055C280.274,-151.887 285.547,-141.912 290.35,-132.824"/>
<polygon fill="black" stroke="black" points="293.547,-134.266 295.126,-123.789 287.358,-130.994 293.547,-134.266"/>
</g>
<!-- a7&#45;&gt;a8 -->
<g id="edge13" class="edge"><title>a7&#45;&gt;a8</title>
<path fill="none" stroke="black" stroke-dasharray="1,5" d="M306.472,-87.6966C307.574,-79.9827 308.898,-70.7125 310.127,-62.1124"/>
<polygon fill="black" stroke="black" points="313.607,-62.4988 311.557,-52.1043 306.677,-61.5088 313.607,-62.4988"/>
</g>
<!-- start -->
<g id="node10" class="node"><title>start</title>
<ellipse fill="none" stroke="black" cx="282" cy="-552" rx="33.2948" ry="18"/>
<text text-anchor="middle" x="282" y="-548.3" font-family="Times,serif" font-size="14.00">start</text>
</g>
<!-- start&#45;&gt;a0 -->
<g id="edge1" class="edge"><title>start&#45;&gt;a0</title>
<path fill="none" stroke="black" d="M282,-533.7C282,-525.245 282,-514.869 282,-505.373"/>
<polygon fill="black" stroke="black" points="285.5,-505.176 282,-495.176 278.5,-505.176 285.5,-505.176"/>
</g>
</g>
</svg>
''')

		TestPipeline testPipeline = new TestPipeline(rawScript)
		testPipeline.run()
	}

}
